environment:
  sonar_auth_token:
    secure: EncryptedSonarAuthToken

init:
- REG ADD "HKLM\Software\Microsoft\Command Processor" /v Autorun /t REG_SZ /d "chcp 65001>nul" /f
- choco install "msbuild-sonarqube-runner" -y

before_build:
- nuget restore
- MSBuild.SonarQube.Runner.exe begin /k:"ostool1cd" /d:"sonar.organization=sonar-opensource-add" /d:"sonar.host.url=https://sonar.silverbulleters.org" /d:"sonar.login=${env.EncryptedSonarAuthToken}"

build_script:
- msbuild "ostool1cd.sln"

after_build:
- MSBuild.SonarQube.Runner.exe end
